### ISSUE TITLE
/tp does not save location

### ISSUE THREAD

**Issue by pmdevita** [pmdevita/StayPut#1]
When `/tp`ing a player to another (`/tp player1 player2`) and that player is another world, the location is not saved. 

Add event listener to catch this kind of tp event

**Comment by edcous** [comment]
any updates on this?

**Comment by edcous** [comment]
`hhh`

**Comment by pmdevita** [comment]
Ah I forgot about this. I'll fix this soon, shouldn't be difficult.

**Comment by edcous** [comment]
Thanks!

**Comment by edcous** [comment]
Can you make it when /mv tp <world> also triggers that?

**Comment by pmdevita** [comment]
/mv tp does work right now, I think it's just /tp that doesn't

**Comment by edcous** [comment]
Huh, it’s not working for me.

**Comment by pmdevita** [comment]
Did you give out the stayput.use permission?

**Comment by edcous** [comment]
I thought so lemme check

**Comment by pmdevita** [comment]
Let me know if you are able to get /mv tp working on the current version, the new fix for /tp probably won't work if /mv tp doesn't work right now.

**Comment by edcous** [comment]
It’s not working

**Comment by edcous** [comment]
is it a problem i am using 1.15.2?

**Comment by edcous** [comment]
I put it in debug mode and saw this:
`>.... [16:40:08 INFO]: [StayPut] PlayerTeleportEvent activated
>.... [16:40:08 INFO]: [StayPut] Player teleporting: computerguy2000
>.... [16:40:08 INFO]: [StayPut] Player teleporting from world: EliAri
>.... [16:40:08 INFO]: [StayPut] Player teleporting to world: lobby
>.... [16:40:08 INFO]: [StayPut] Saving computerguy2000 (a30f47d4-3018-4485-a2d0-559a8dc0378c)'s location in >EliAri<
>.... [16:40:08 INFO]: [StayPut] Not teleporting player because there is no previous location found `

**Comment by edcous** [comment]
I put it in debug mode and saw this:
`>.... [16:40:08 INFO]: [StayPut] PlayerTeleportEvent activated
>.... [16:40:08 INFO]: [StayPut] Player teleporting: myusername
>.... [16:40:08 INFO]: [StayPut] Player teleporting from world: [world1]
>.... [16:40:08 INFO]: [StayPut] Player teleporting to world: lobby
>.... [16:40:08 INFO]: [StayPut] Saving myusername (myusername)'s location in >[world1]<
>.... [16:40:08 INFO]: [StayPut] Not teleporting player because there is no previous location found `

**Comment by pmdevita** [comment]
Are you using SQLite?

**Comment by edcous** [comment]
I was, but I also tried using MySQL.

**Comment by pmdevita** [comment]
Yeah I'll make it

**Comment by pmdevita** [comment]
Should be resolved with 1.3
