### ISSUE TITLE
blacklist doesnt seem to work or bugged

### ISSUE THREAD

**Issue by DeathGOD7** [pmdevita/StayPut#10]
Hi I was wondering if you could
- add ability to add worlds in different group and toggle whether to save last position of that group/worlds.
- reset the saved last position of player when they dies so they will be at spawn of world (for compatible with ESSx Spawn where players are sent to spawn/hub world. and if they tries to come back to survival world they will be at spawn/or their bed than their last world location.)

and even if i black list the hub in config and restart the server, it saves the location and tp me there when i tp back

Thank You

**Comment by pmdevita** [comment]
The first point is the same as #8 

The second one sounds like the blacklist is broken. I'll take a look when I can

**Comment by DeathGOD7** [comment]
Thank you :D

**Comment by pmdevita** [comment]
I'm going to close this since we've had a release since this issue was opened. Feel free to open this again if you're still having trouble. If you can, try turning debug mode on and pasting in your server logs, you should probably also send your config too.

**Comment by pmdevita** [comment]
2.1.0 will now print the blacklisted world list in debug mode, that should help narrow down the problem if it's still occurring.
