### ISSUE TITLE
Not rly an Issue

### ISSUE THREAD

**Issue by LevoSmetalo02** [pmdevita/StayPut#12]
I need plugin for my server that will remember last position in world and i used [https://dev.bukkit.org/projects/worldpos](url), and it worked great (even i was in 1.17.1) because i didnt need to get perms of multi verse core to other people, but i now have problem where i need to merge last location of 4 worlds into one.
What i mean is that i have lets say world1(Spawn), world2(Survival), world3(Nether), world4(End), and if player was in nether and exit i can send them again back to last location of just one of that worlds, and if my "world selector" is set to /world Spawn, it will teleport them to spawn, even if they were the last in nether

Im creating server for me and frends with multiple world and minigames, so if you can do me a favor and create something like this or change your or somehow that one "WorldPos" i will really be thankful.

**Comment by pmdevita** [comment]
I'm not entirely sure what you are looking for but I think you are talking about world groups, here's the issue for it https://github.com/pmdevita/StayPut/issues/8

This will add support for tracking a single location across multiple worlds, most useful for combining overworld, nether, and the end worlds but I'll add some customization support as well.

I'm closing the issue but feel free to reopen it if I misunderstood.
