### ISSUE TITLE
Update to 1.18.2

### ISSUE THREAD

**Issue by joex92** [pmdevita/StayPut#14]
i'm finally updating the server to 1.18.2, and this is one of those essential plugins that are not working anymore, please update it...

**Comment by pmdevita** [comment]
I'll take a look over the next few days

**Comment by pmdevita** [comment]
The 1.18 problems seem to stem from Java 9+ MySQL requiring explicitly defined TLS protocols. This has been set to 1.2 for now in the 2.0.0 beta but I'll probably make it configurable later
