### ISSUE TITLE
2.0.0 beta Database Changes - Feedback needed

### ISSUE THREAD

**Issue by pmdevita** [pmdevita/StayPut#15]
The 2.0.0 beta introduces a full rewrite of the database code, with a migration system to move server databases from the old schema to the new one. However, I am not 100% confident my implementation will work for everyone so I'd like for people to test out the plugin with debug mode enabled and double check that the migration occurs and that the plugin operates as expected afterwards. 

Thank you all for your help!

**Comment by zax71** [comment]
I might be having Migration issues. I get [this](https://paste.gg/p/Zax71/9b5c0be813444a80a347fb8c431de3c9) error when an old player joins, from pre 2.0

**Comment by pmdevita** [comment]
Can you enable debug mode in the configuration and send me what StayPut outputs on server start up?

**Comment by zax71** [comment]
https://bin.bloom.host/xifanusite

**Comment by pmdevita** [comment]
Ah looks like it doesn't detect you need to migrate, let's see

**Comment by pmdevita** [comment]
Can you send me the start up logs with this one?
[StayPut-2.0.0b.zip](https://github.com/pmdevita/StayPut/files/9128345/StayPut-2.0.0b.zip)

**Comment by zax71** [comment]
https://bin.bloom.host/rimuleyupe

**Comment by zax71** [comment]
I’ll have a look when another old player joins… could take a while

**Comment by VanishCZE** [comment]
https://paste.gg/p/anonymous/874ac48b5b9445248e6d329cc9aaaa33

**Comment by zax71** [comment]
> I’ll have a look when another old player joins… could take a while

I haven’t had the issue again yet. So I think it works :)

**Comment by VanishCZE** [comment]
![image](https://user-images.githubusercontent.com/98617269/189483931-58c867da-043f-4556-841d-0d1952ccc12f.png)

**Comment by VanishCZE** [comment]
https://paste.gg/p/anonymous/93f29ec872054d8f8339856772202ace

**Comment by MykalsVapor** [comment]
downloaded the 2.0.0b.zip and havent had any issues.  im using apex hosting with paper 1.19.2 and around 50 or so plugins.  this works exactly like i need it to... good job :)

**Comment by PystoyPlayer** [comment]
As far as I understand, the plugin a bit slowly teleports to the save point. I made it so that in the "spawn" region the player gets /randomteleport , but worldguard processes it so quickly that it is ahead of your plugin, and even if the player has a savepoint, worldguard thinks that player is still at spawn and prescribes /rtp

**Comment by pmdevita** [comment]
> As far as I understand, the plugin a bit slowly teleports to the save point. I made it so that in the "spawn" region the player gets /randomteleport , but worldguard processes it so quickly that it is ahead of your plugin, and even if the player has a savepoint, worldguard thinks that player is still at spawn and prescribes /rtp

Huh, somehow I never thought about event handling priority, but that might solve some of the annoying business caused by other plugins changing the world spawn, I'll look into it https://github.com/pmdevita/StayPut/issues/23

**Comment by PystoyPlayer** [comment]
> > As far as I understand, the plugin a bit slowly teleports to the save point. I made it so that in the "spawn" region the player gets /randomteleport , but worldguard processes it so quickly that it is ahead of your plugin, and even if the player has a savepoint, worldguard thinks that player is still at spawn and prescribes /rtp
> 
> Huh, somehow I never thought about event handling priority, but that might solve some of the annoying business caused by other plugins changing the world spawn, I'll look into it #23

In principle, I came up with a fairly easy solution) It remains to figure out how to remove / confirm (since the spawn is in the air) [https://www.veed.io/view/c9ae240e-f8a8-4779-86e7-69887a6fdb40?panel=share&sharingWidget=true](url)

**Comment by PystoyPlayer** [comment]
quit on a death menu save location with full health

**Comment by PystoyPlayer** [comment]
https://www.veed.io/view/c8853ea5-8286-4316-b52a-9b1e646eb0e6?panel=share

**Comment by pmdevita** [comment]
It seems that the 2.0.0 database changes went over well so I'm going to close this issue now.
