### ISSUE TITLE
Keep teleporting to spawn when switching worlds

### ISSUE THREAD

**Issue by WolfyRed** [pmdevita/StayPut#16]
I keep teleporting to spawn when switching to world "world", every other world works as expected, you teleport to the last location you were at in those worlds, but switching to world "world" sends you straight to spawn.

/version: This server is running Paper version git-Paper-657 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Comment by pmdevita** [comment]
I'm guessing you figured it out? If you have time, I'd appreciate it if you try the new beta, you can find it on the releases page

**Comment by WolfyRed** [comment]
That beta crashed each time I turned on the server

**Comment by pmdevita** [comment]
Can you send me the error?

**Comment by WolfyRed** [comment]
https://mclo.gs/YFbgnFs

**Comment by pmdevita** [comment]
That's super weird, does the old version still work? If it's alright, can you send me your .db file in the StayPut folder?

**Comment by WolfyRed** [comment]
OK
[database.zip](https://github.com/pmdevita/StayPut/files/8995817/database.zip)

**Comment by pmdevita** [comment]
What version of Java are you using?
