### ISSUE TITLE
Quit from death title doesn't reset your location

### ISSUE THREAD

**Issue by PystoyPlayer** [pmdevita/StayPut#24]
If u die and quit from "death menu" StayPut will remember your location and after respawn teleport you back so you don't lose anything 
https://www.veed.io/view/c8853ea5-8286-4316-b52a-9b1e646eb0e6?panel=share

**Comment by PystoyPlayer** [comment]
> Oh nice catch

would you fix it ?

**Comment by pmdevita** [comment]
Yep

**Comment by pmdevita** [comment]
Probably in around 2-3 weeks when my IRL responsibilities die down again

**Comment by PystoyPlayer** [comment]
> Probably in around 2-3 weeks when my IRL responsibilities die down again

How is it going ?

**Comment by PystoyPlayer** [comment]
@pmdevita ?

**Comment by pmdevita** [comment]
OK I ended up having time tonight so I think I can do the release tonight. Just FYI, sometimes I might not get to an issue timely but if I allow it to be open on the issue tracker, that means I've recognized it and will, at least eventually, get to it.

Anyhow, this is fixed now but there's a bit of catch. It will not work perfectly if the plugin is running in compatibility mode with the previous version's database table (if you were using anything pre-2.0.0a and then started using 2.0.0a+, you'll be in compatibility mode). So it might not work until your server doesn't need the old database table anymore. 

Once it's 100% certain the migration does work and doesn't cause any data loss, I'd be comfortable fixing this for compatibility mode. I'll leave the issue open for now just to keep a reminder.

**Comment by pmdevita** [comment]
It seems that the 2.0.0 changes worked out so I'm going to fix this for servers running in compatibility mode too now.

**Comment by pmdevita** [comment]
Will be completely fixed in 2.1.0!

**Comment by PystoyPlayer** [comment]
> Will be completely fixed in 2.1.0!

Great! How soon it will be ?
