### ISSUE TITLE
1.20 support?

### ISSUE THREAD

**Issue by jshmania** [pmdevita/StayPut#33]
The plugin doesn't seem to be working properly on 1.20.1. When I leave and rejoin a world, it puts me back to the world spawn. This started happening when I updated my server to 1.20. There aren't any errors in the console.

**Comment by pmdevita** [comment]
That's strange, maybe your spawn got reset? If you're OK with it, try setting your spawn again with `/mv set spawn` and see if that fixes it. There shouldn't be any incompatibility problems as far as I'm aware, the plugin is only really reliant on teleport related things and those don't really get changed.

**Comment by pmdevita** [comment]
Coming back to this, could you turn on debug mode and send me the logs when you teleport?

**Comment by jshmania** [comment]
It was because of MV spawn being unset. Don't know why it decided to remove the one I'd originally setup though.

**Comment by pmdevita** [comment]
Ah interesting. I'll close the issue then.
