### ISSUE TITLE
Handle world groups?

### ISSUE THREAD

**Issue by KairuByte** [pmdevita/StayPut#8]
Is there any way to handle world groups gracefully?

I'm hoping to be able to specify world, world_nether and world_the_end to all be considered when teleporting in. So if the last location on any of the worlds was in world_nether, that is where the player would end up, regardless of attempting to teleport into any of the others in the group.

**Comment by pmdevita** [comment]
This is something I still need to fix. I forgot to add an issue for it though so thanks for making this.

**Comment by KairuByte** [comment]
Any idea when the issue might get a little attention?

**Comment by pmdevita** [comment]
I'm getting close to finishing all the big stuff for the semester, I'll try to tackle it soon.

**Comment by kingerona** [comment]
Hello good sir, any update on the issue. Would be a biggie, thanks for the plugin though!

**Comment by pmdevita** [comment]
Yeah, I realize I've been putting this off for too long. My semester is done now so once I wrap up a couple things, this is going to be my main focus.

**Comment by pmdevita** [comment]
I was able to start some work on the rewrite but I unfortunately had to put it on hold to find a new job. I'll try to pick it back up as soon as I can.

**Comment by pmdevita** [comment]
Forgot to add, the groundwork was laid for world groups in the 2.0.0 beta, right now it automatically groups the overworld and its nether and end worlds, but it will be configurable in the future

**Comment by KairuByte** [comment]
That's actually pretty much all I needed it for, but configuration will likely be nice for some out there who want to have different overworlds and such linked.

Thank you!

**Comment by pmdevita** [comment]
2.0.0 is released, I'm going to start a new issue for customizable world groups.
